//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Setup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Setup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than $10,000
        ///$10,000 to $24,000
        ///$24,000 to $40,000
        ///$40,000 to $75,000
        ///$75,000 to $150,000
        ///$150,000 to $250,000
        ///More than $250,000.
        /// </summary>
        internal static string AnnualHouseholdIncome {
            get {
                return ResourceManager.GetString("AnnualHouseholdIncome", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] KillOption {
            get {
                object obj = ResourceManager.GetObject("KillOption", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KillPanl {
            get {
                object obj = ResourceManager.GetObject("KillPanl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KillTimr {
            get {
                object obj = ResourceManager.GetObject("KillTimr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KillTray {
            get {
                object obj = ResourceManager.GetObject("KillTray", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Icon oxigen {
            get {
                object obj = ResourceManager.GetObject("oxigen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap oxigen_banner_1 {
            get {
                object obj = ResourceManager.GetObject("oxigen_banner_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom,,
        ///,Aberdeen,
        ///,Belfast,
        ///,Birmingham,
        ///,Blackburn,
        ///,Blackpool,
        ///,Bolton,
        ///,Bournemouth,
        ///,Bradford,
        ///,Brighton,
        ///,Bristol,
        ///,Cambridge,
        ///,Cardiff,
        ///,Cheltenham,
        ///,Colchester,
        ///,Coventry,
        ///,Crawley,
        ///,Derby,
        ///,Dudley,
        ///,Dundee,
        ///,Eastbourne,
        ///,Edinburgh,
        ///,Exeter,
        ///,Glasgow,
        ///,Gloucester,
        ///,Huddersfield,
        ///,Ipswich,
        ///,Kingston upon Hull,
        ///,Leeds,
        ///,Leicester,
        ///,Liverpool,
        ///,London,
        ///,Luton,
        ///,Manchester,
        ///,Middlesbrough,
        ///,Milton Keynes,
        ///,Newcastle upon Tyne,
        ///,Newport,
        ///,Northampton,
        ///,Norw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OxigenCountryList {
            get {
                return ResourceManager.GetString("OxigenCountryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper management
        ///Middle management
        ///Supervisor
        ///White-collar worker
        ///Skilled worker / Tradesman
        ///Unskilled worker
        ///Student
        ///Retired
        ///Unemployed.
        /// </summary>
        internal static string OxigenEmploymentLevels {
            get {
                return ResourceManager.GetString("OxigenEmploymentLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting
        ///Advertising
        ///Arts &amp; Entertainment
        ///Charity / Voluntary
        ///Community &amp; Social Services
        ///Construction &amp; Architecture
        ///Customer Service / Call Centre
        ///Education, Training, Library
        ///Engineering / Utilities / Energy
        ///Finance &amp; Economics
        ///Healthcare
        ///Hospitality &amp; Catering
        ///HR
        ///IT / Computing
        ///Legal
        ///Management &amp; Executive
        ///Manufacturing &amp; Production
        ///Marketing &amp; PR
        ///Media / Digital / Creative
        ///Military
        ///Motoring &amp; Automotive
        ///Public Sector
        ///Recruitment
        ///Retail
        ///Retired
        ///Sales
        ///Scientific
        ///Secretarial,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OxigenOccupations {
            get {
                return ResourceManager.GetString("OxigenOccupations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang2057\deflangfe2057\themelang2057\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\f39\fbidi \fswiss\fcharset0\fprq2{\*\panose 00000000000000000000}Microsoft Sans Serif;}{\flomajor\f31500\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times Ne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OxigenTermsOfService {
            get {
                return ResourceManager.GetString("OxigenTermsOfService", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap questionmark {
            get {
                object obj = ResourceManager.GetObject("questionmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
