//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxigenIISitesBLServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OxigenIISitesBLServices.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donotreply@oxigen.net.
        /// </summary>
        internal static string PasswordRemindEmailFrom {
            get {
                return ResourceManager.GetString("PasswordRemindEmailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for contacting Oxigen for your password reminder. Your password is:{0}{0}{1}{0}{0}You can update your details in the My Account section of the website or if you need any further assistance please see the Help section.{0}{0}Kind Regards,{0}The Oxigen Team.
        /// </summary>
        internal static string PasswordRemindEmailMessage {
            get {
                return ResourceManager.GetString("PasswordRemindEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxigen Password.
        /// </summary>
        internal static string PasswordRemindEmailSubject {
            get {
                return ResourceManager.GetString("PasswordRemindEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donotreply@oxigen.net.
        /// </summary>
        internal static string PasswordRequestEmailFrom {
            get {
                return ResourceManager.GetString("PasswordRequestEmailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, {1}! You have a new request from someone that would like to follow one of your Streams!{0}{0}Stream: {2}{0}Requested by: {3}{0}Email Address: {4}{0}{0}Message: {5}{0}{0}Kinds Regards,{0}The Oxigen Team.
        /// </summary>
        internal static string PasswordRequestEmailMessage {
            get {
                return ResourceManager.GetString("PasswordRequestEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone liked your stream!.
        /// </summary>
        internal static string PasswordRequestEmailSubject {
            get {
                return ResourceManager.GetString("PasswordRequestEmailSubject", resourceCulture);
            }
        }
    }
}
