//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxigenIITest {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Documents and Settings\\MichaliKonstantinidi\\My Documents\\OxigenIIData\\Settings" +
            "Data\\ss_play_list.dat")]
        public string PlaylistDataPath {
            get {
                return ((string)(this["PlaylistDataPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Documents and Settings\\MichaliKonstantinidi\\My Documents\\OxigenIIData\\Settings" +
            "Data\\ss_general_data.dat")]
        public string GeneralDataPath {
            get {
                return ((string)(this["GeneralDataPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Documents and Settings\\MichaliKonstantinidi\\My Documents\\OxigenIIData\\Settings" +
            "Data\\ss_adcond_data.dat")]
        public string AdvertDataPath {
            get {
                return ((string)(this["AdvertDataPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Documents and Settings\\MichaliKonstantinidi\\My Documents\\OxigenIIData\\Settings" +
            "Data\\ss_demo_data.dat")]
        public string DemographicDataPath {
            get {
                return ((string)(this["DemographicDataPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Documents and Settings\\MichaliKonstantinidi\\My Documents\\OxigenIIData\\Settings" +
            "Data\\ss_channel_subscription_data.dat")]
        public string UserChannelSubscriptionsPath {
            get {
                return ((string)(this["UserChannelSubscriptionsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Documents and Settings\\MichaliKonstantinidi\\My Documents\\OxigenIIData\\ChannelD" +
            "ata\\")]
        public string ChannelDataPath {
            get {
                return ((string)(this["ChannelDataPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Documents and Settings\\MichaliKonstantinidi\\My Documents\\OxigenIIData\\OxigenDe" +
            "bug.txt")]
        public string DebugPath {
            get {
                return ((string)(this["DebugPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Documents and Settings\\MichaliKonstantinidi\\My Documents\\OxigenIIData\\Assets\\")]
        public string AssetPath {
            get {
                return ((string)(this["AssetPath"]));
            }
        }
    }
}
