//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxigenIIAdvertising.SoftwareUpdater.UserFileMarshallerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserMain", Namespace="http://schemas.datacontract.org/2004/07/OxigenIIAdvertising.UserManagementService" +
        "s")]
    [System.SerializableAttribute()]
    public partial class UserMain : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OxigenIIAdvertising.SoftwareUpdater.UserFileMarshallerService.DemographicData UserDemographicDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OxigenIIAdvertising.SoftwareUpdater.UserFileMarshallerService.DemographicData UserDemographicData {
            get {
                return this.UserDemographicDataField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDemographicDataField, value) != true)) {
                    this.UserDemographicDataField = value;
                    this.RaisePropertyChanged("UserDemographicData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DemographicData", Namespace="http://schemas.datacontract.org/2004/07/OxigenIIAdvertising.UserManagementService" +
        "s")]
    [System.SerializableAttribute()]
    public partial class DemographicData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OxigenIIAdvertising.SoftwareUpdater.UserFileMarshallerService.Gender GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocioEconomicGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OxigenIIAdvertising.SoftwareUpdater.UserFileMarshallerService.Gender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocioEconomicGroup {
            get {
                return this.SocioEconomicGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.SocioEconomicGroupField, value) != true)) {
                    this.SocioEconomicGroupField = value;
                    this.RaisePropertyChanged("SocioEconomicGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://schemas.datacontract.org/2004/07/OxigenIIAdvertising.UserManagementService" +
        "s")]
    public enum Gender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserFileMarshallerService.IUserManagementServices")]
    public interface IUserManagementServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementServices/GetUserDetails", ReplyAction="http://tempuri.org/IUserManagementServices/GetUserDetailsResponse")]
        OxigenIIAdvertising.SoftwareUpdater.UserFileMarshallerService.UserMain GetUserDetails(string username, string userPassword, string userGUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementServices/RegisterNewMachine", ReplyAction="http://tempuri.org/IUserManagementServices/RegisterNewMachineResponse")]
        string RegisterNewMachine(string username, string userPassword, string userGUID, string machineGUID, string machineMACAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementServices/RegisterNewUser", ReplyAction="http://tempuri.org/IUserManagementServices/RegisterNewUserResponse")]
        void RegisterNewUser(string userGUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementServices/GetUserDemographicData", ReplyAction="http://tempuri.org/IUserManagementServices/GetUserDemographicDataResponse")]
        OxigenIIAdvertising.SoftwareUpdater.UserFileMarshallerService.DemographicData GetUserDemographicData(string username, string userPassword, string userGUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementServices/GetUserChannelSubscriptions", ReplyAction="http://tempuri.org/IUserManagementServices/GetUserChannelSubscriptionsResponse")]
        string GetUserChannelSubscriptions(string username, string userPassword, string userGUID, string MachineGUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementServices/SendForgottenPassword", ReplyAction="http://tempuri.org/IUserManagementServices/SendForgottenPasswordResponse")]
        void SendForgottenPassword(string username, string userPassword, string userGUID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IUserManagementServicesChannel : OxigenIIAdvertising.SoftwareUpdater.UserFileMarshallerService.IUserManagementServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class UserManagementServicesClient : System.ServiceModel.ClientBase<OxigenIIAdvertising.SoftwareUpdater.UserFileMarshallerService.IUserManagementServices>, OxigenIIAdvertising.SoftwareUpdater.UserFileMarshallerService.IUserManagementServices {
        
        public UserManagementServicesClient() {
        }
        
        public UserManagementServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagementServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OxigenIIAdvertising.SoftwareUpdater.UserFileMarshallerService.UserMain GetUserDetails(string username, string userPassword, string userGUID) {
            return base.Channel.GetUserDetails(username, userPassword, userGUID);
        }
        
        public string RegisterNewMachine(string username, string userPassword, string userGUID, string machineGUID, string machineMACAddress) {
            return base.Channel.RegisterNewMachine(username, userPassword, userGUID, machineGUID, machineMACAddress);
        }
        
        public void RegisterNewUser(string userGUID) {
            base.Channel.RegisterNewUser(userGUID);
        }
        
        public OxigenIIAdvertising.SoftwareUpdater.UserFileMarshallerService.DemographicData GetUserDemographicData(string username, string userPassword, string userGUID) {
            return base.Channel.GetUserDemographicData(username, userPassword, userGUID);
        }
        
        public string GetUserChannelSubscriptions(string username, string userPassword, string userGUID, string MachineGUID) {
            return base.Channel.GetUserChannelSubscriptions(username, userPassword, userGUID, MachineGUID);
        }
        
        public void SendForgottenPassword(string username, string userPassword, string userGUID) {
            base.Channel.SendForgottenPassword(username, userPassword, userGUID);
        }
    }
}
