//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxigenIIAdvertising.SSGService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OxigenIIAdvertising.SSGService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open OxigenCE.
        /// </summary>
        internal static string ErrorOpeningContentExchanger {
            get {
                return ResourceManager.GetString("ErrorOpeningContentExchanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve General Data.
        /// </summary>
        internal static string ErrorOpeningGeneralData {
            get {
                return ResourceManager.GetString("ErrorOpeningGeneralData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open OxigenLE.
        /// </summary>
        internal static string ErrorOpeningLogExchanger {
            get {
                return ResourceManager.GetString("ErrorOpeningLogExchanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open OxigenSU.
        /// </summary>
        internal static string ErrorOpeningSoftwareUpdater {
            get {
                return ResourceManager.GetString("ErrorOpeningSoftwareUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overflow when reading timer values.
        /// </summary>
        internal static string ErrorOverflowTimerValues {
            get {
                return ResourceManager.GetString("ErrorOverflowTimerValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve Timer values.
        /// </summary>
        internal static string ErrorRetrievingTimerValues {
            get {
                return ResourceManager.GetString("ErrorRetrievingTimerValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start communication channel.
        /// </summary>
        internal static string ErrorStartingCommunicationChannel {
            get {
                return ResourceManager.GetString("ErrorStartingCommunicationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to gracefully stop communication channel.
        /// </summary>
        internal static string ErrorStoppingCommunicationChannel {
            get {
                return ResourceManager.GetString("ErrorStoppingCommunicationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer interval invalid.
        /// </summary>
        internal static string ErrorTimerIntervalInvalid {
            get {
                return ResourceManager.GetString("ErrorTimerIntervalInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxigen Service Continuing.
        /// </summary>
        internal static string ServiceContinue {
            get {
                return ResourceManager.GetString("ServiceContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxigen Service Paused.
        /// </summary>
        internal static string ServicePaused {
            get {
                return ResourceManager.GetString("ServicePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxigen Service Started.
        /// </summary>
        internal static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxigen Service Stopped.
        /// </summary>
        internal static string ServiceStopped {
            get {
                return ResourceManager.GetString("ServiceStopped", resourceCulture);
            }
        }
    }
}
