//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxigenIIAdvertising.ScreenSaver7.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OxigenIIAdvertising.ScreenSaver7.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Fatal Error has occured. Please run install to repair your installation..
        /// </summary>
        internal static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A setting was not found in your current settings. Please press space bar to invoke the Content Exchanger..
        /// </summary>
        internal static string GeneralDataParameterNotFound {
            get {
                return ResourceManager.GetString("GeneralDataParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no assets to display.
        /// </summary>
        internal static string NoAssets {
            get {
                return ResourceManager.GetString("NoAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration files have no read and write access rights. Please change access rights to thos files or contact your system administrator..
        /// </summary>
        internal static string NoConfFileRights {
            get {
                return ResourceManager.GetString("NoConfFileRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error information has no read and write access rights. Please change access eights to the file or contact your system administrator..
        /// </summary>
        internal static string NoDebugFileRights {
            get {
                return ResourceManager.GetString("NoDebugFileRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General configuration file not found. Please press space bar to repair the installation.
        /// </summary>
        internal static string NoGeneralData {
            get {
                return ResourceManager.GetString("NoGeneralData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files have no read and write access rights. Please change access rights to those files or contact your system administrator..
        /// </summary>
        internal static string NoLogFileRights {
            get {
                return ResourceManager.GetString("NoLogFileRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No playlist for your screensaver was found. Please press space bar invoke the Content Exchanger.
        /// </summary>
        internal static string NoPlaylist {
            get {
                return ResourceManager.GetString("NoPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the parameters of the General configuration file cannot be read. Please press space bar to repair the installation..
        /// </summary>
        internal static string ParameterNorParseable {
            get {
                return ResourceManager.GetString("ParameterNorParseable", resourceCulture);
            }
        }
    }
}
