BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Templates ADD
	DisplayDuration float(53) NOT NULL CONSTRAINT DF_Templates_DisplayDuration DEFAULT -1
GO
ALTER TABLE dbo.Templates SET (LOCK_ESCALATION = TABLE)
GO
COMMIT