/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Tmp_RSSFeeds
	(
	RSSFEED_ID int NOT NULL IDENTITY (1, 1),
	PublisherID int NOT NULL,
	TemplateID int NOT NULL,
	ChannelID int NOT NULL,
	SlideFolderID int NOT NULL,
	Name nvarchar(100) NOT NULL,
	URL nvarchar(1000) NOT NULL,
	XSLT ntext NOT NULL,
	LastItem nvarchar(1000) NULL,
	LastChecked datetime NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_RSSFeeds SET (LOCK_ESCALATION = TABLE)
GO
SET IDENTITY_INSERT dbo.Tmp_RSSFeeds ON
GO
IF EXISTS(SELECT * FROM dbo.RSSFeeds)
	 EXEC('INSERT INTO dbo.Tmp_RSSFeeds (RSSFEED_ID, PublisherID, TemplateID, ChannelID, SlideFolderID, Name, URL, XSLT, LastItem, LastChecked)
		SELECT RSSFEED_ID, PublisherID, TemplateID, ChannelID, SlideFolderID, Name, URL, CONVERT(ntext, XSLT), LastItem, LastChecked FROM dbo.RSSFeeds WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_RSSFeeds OFF
GO
DROP TABLE dbo.RSSFeeds
GO
EXECUTE sp_rename N'dbo.Tmp_RSSFeeds', N'RSSFeeds', 'OBJECT' 
GO
ALTER TABLE dbo.RSSFeeds ADD CONSTRAINT
	PK_RSSFeed PRIMARY KEY CLUSTERED 
	(
	RSSFEED_ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
COMMIT