//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleInstaller {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleInstaller.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] AdvertList {
            get {
                object obj = ResourceManager.GetObject("AdvertList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AssetLevel {
            get {
                object obj = ResourceManager.GetObject("AssetLevel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Assets {
            get {
                object obj = ResourceManager.GetObject("Assets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AssetScheduling {
            get {
                object obj = ResourceManager.GetObject("AssetScheduling", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AssetType {
            get {
                object obj = ResourceManager.GetObject("AssetType", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AxInterop_QTOControlLib {
            get {
                object obj = ResourceManager.GetObject("AxInterop_QTOControlLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AxInterop_ShockwaveFlashObjects {
            get {
                object obj = ResourceManager.GetObject("AxInterop_ShockwaveFlashObjects", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AxInterop_WMPLib {
            get {
                object obj = ResourceManager.GetObject("AxInterop_WMPLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BoolContainerLib {
            get {
                object obj = ResourceManager.GetObject("BoolContainerLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ChannelData {
            get {
                object obj = ResourceManager.GetObject("ChannelData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ChannelSubscriptions {
            get {
                object obj = ResourceManager.GetObject("ChannelSubscriptions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Demographic {
            get {
                object obj = ResourceManager.GetObject("Demographic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DemographicRange {
            get {
                object obj = ResourceManager.GetObject("DemographicRange", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] EncryptionDecryption {
            get {
                object obj = ResourceManager.GetObject("EncryptionDecryption", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Exceptions {
            get {
                object obj = ResourceManager.GetObject("Exceptions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FileChecksumCalculator {
            get {
                object obj = ResourceManager.GetObject("FileChecksumCalculator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FileLocker {
            get {
                object obj = ResourceManager.GetObject("FileLocker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FileRightsChecker {
            get {
                object obj = ResourceManager.GetObject("FileRightsChecker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GeneralData {
            get {
                object obj = ResourceManager.GetObject("GeneralData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InclusionExclusionRules {
            get {
                object obj = ResourceManager.GetObject("InclusionExclusionRules", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InterCommunicationStructures {
            get {
                object obj = ResourceManager.GetObject("InterCommunicationStructures", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InternetConnectionCheck {
            get {
                object obj = ResourceManager.GetObject("InternetConnectionCheck", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Interop_QTOControlLib {
            get {
                object obj = ResourceManager.GetObject("Interop_QTOControlLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Interop_QTOLibrary {
            get {
                object obj = ResourceManager.GetObject("Interop_QTOLibrary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Interop_SHDocVw {
            get {
                object obj = ResourceManager.GetObject("Interop_SHDocVw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Interop_ShockwaveFlashObjects {
            get {
                object obj = ResourceManager.GetObject("Interop_ShockwaveFlashObjects", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Interop_WMPLib {
            get {
                object obj = ResourceManager.GetObject("Interop_WMPLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LinqToHashSet {
            get {
                object obj = ResourceManager.GetObject("LinqToHashSet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LogEntry {
            get {
                object obj = ResourceManager.GetObject("LogEntry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LogFileReader {
            get {
                object obj = ResourceManager.GetObject("LogFileReader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LogFileWriter {
            get {
                object obj = ResourceManager.GetObject("LogFileWriter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LoggerInfo {
            get {
                object obj = ResourceManager.GetObject("LoggerInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LogStats {
            get {
                object obj = ResourceManager.GetObject("LogStats", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LogWriteOperations {
            get {
                object obj = ResourceManager.GetObject("LogWriteOperations", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NoAssetsAnimator {
            get {
                object obj = ResourceManager.GetObject("NoAssetsAnimator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Oxigen {
            get {
                object obj = ResourceManager.GetObject("Oxigen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;sectionGroup name=&quot;applicationSettings&quot; type=&quot;System.Configuration.ApplicationSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; &gt;
        ///            &lt;section name=&quot;OxigenIIAdvertising.ScreenSaver.Properties.Settings&quot; type=&quot;System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; requirePermission=&quot;false&quot; /&gt;
        ///            &lt;sect [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Oxigen_scr {
            get {
                return ResourceManager.GetString("Oxigen_scr", resourceCulture);
            }
        }
        
        internal static byte[] OxigenCE {
            get {
                object obj = ResourceManager.GetObject("OxigenCE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;sectionGroup name=&quot;applicationSettings&quot; type=&quot;System.Configuration.ApplicationSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; &gt;
        ///            &lt;section name=&quot;OxigenIIAdvertising.ContentExchanger.Settings&quot; type=&quot;System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; requirePermission=&quot;false&quot; /&gt;
        ///            &lt;section na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OxigenCE_exe {
            get {
                return ResourceManager.GetString("OxigenCE_exe", resourceCulture);
            }
        }
        
        internal static byte[] OxigenCompiledRegexes {
            get {
                object obj = ResourceManager.GetObject("OxigenCompiledRegexes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OxigenLE {
            get {
                object obj = ResourceManager.GetObject("OxigenLE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;sectionGroup name=&quot;applicationSettings&quot; type=&quot;System.Configuration.ApplicationSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; &gt;
        ///      &lt;section name=&quot;OxigenIIAdvertising.LogExchanger.Properties.Settings&quot; type=&quot;System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; requirePermission=&quot;false&quot; /&gt;
        ///    &lt;/sectionGroup&gt;
        ///  &lt;/con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OxigenLE_exe {
            get {
                return ResourceManager.GetString("OxigenLE_exe", resourceCulture);
            }
        }
        
        internal static byte[] OxigenService {
            get {
                object obj = ResourceManager.GetObject("OxigenService", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;sectionGroup name=&quot;userSettings&quot; type=&quot;System.Configuration.UserSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; &gt;
        ///      &lt;section name=&quot;OxigenIIAdvertising.SSGService.Settings&quot; type=&quot;System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; allowExeDefinition=&quot;MachineToLocalUser&quot; requirePermission=&quot;false&quot; /&gt;
        ///    &lt;/sectionGr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OxigenService_exe {
            get {
                return ResourceManager.GetString("OxigenService_exe", resourceCulture);
            }
        }
        
        internal static byte[] OxigenServiceFactory {
            get {
                object obj = ResourceManager.GetObject("OxigenServiceFactory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OxigenSingletons {
            get {
                object obj = ResourceManager.GetObject("OxigenSingletons", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OxigenStopwatch {
            get {
                object obj = ResourceManager.GetObject("OxigenStopwatch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OxigenTray {
            get {
                object obj = ResourceManager.GetObject("OxigenTray", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;sectionGroup name=&quot;applicationSettings&quot; type=&quot;System.Configuration.ApplicationSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; &gt;
        ///      &lt;section name=&quot;OxigenIIAdvertising.SSG.Properties.Settings&quot; type=&quot;System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; requirePermission=&quot;false&quot; /&gt;
        ///      &lt;section name=&quot;OxigenIISSG.Prop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OxigenTray_exe {
            get {
                return ResourceManager.GetString("OxigenTray_exe", resourceCulture);
            }
        }
        
        internal static byte[] OxigenUserDataMarshallerClient {
            get {
                object obj = ResourceManager.GetObject("OxigenUserDataMarshallerClient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OxigenUserDataMarshallrContracts {
            get {
                object obj = ResourceManager.GetObject("OxigenUserDataMarshallrContracts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OxigenUserFileMarDataContracts {
            get {
                object obj = ResourceManager.GetObject("OxigenUserFileMarDataContracts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OxigenUserFileMarshallerClient {
            get {
                object obj = ResourceManager.GetObject("OxigenUserFileMarshallerClient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OxigenUserMgmtServicesClient {
            get {
                object obj = ResourceManager.GetObject("OxigenUserMgmtServicesClient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OxigenUserMgmtServicesContracts {
            get {
                object obj = ResourceManager.GetObject("OxigenUserMgmtServicesContracts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PlayerType {
            get {
                object obj = ResourceManager.GetObject("PlayerType", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Playlist {
            get {
                object obj = ResourceManager.GetObject("Playlist", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PlaylistAssetPicker {
            get {
                object obj = ResourceManager.GetObject("PlaylistAssetPicker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PlaylistLogic {
            get {
                object obj = ResourceManager.GetObject("PlaylistLogic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ProgressAnimation {
            get {
                object obj = ResourceManager.GetObject("ProgressAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ProxyClientBaseLib {
            get {
                object obj = ResourceManager.GetObject("ProxyClientBaseLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RegistryAccess {
            get {
                object obj = ResourceManager.GetObject("RegistryAccess", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ScreenSaverConfig {
            get {
                object obj = ResourceManager.GetObject("ScreenSaverConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;sectionGroup name=&quot;applicationSettings&quot; type=&quot;System.Configuration.ApplicationSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; &gt;
        ///            &lt;section name=&quot;OxigenIIScreenSaverConfig.Properties.Settings&quot; type=&quot;System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; requirePermission=&quot;false&quot; /&gt;
        ///        &lt;/sectionGroup&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScreenSaverConfig_exe {
            get {
                return ResourceManager.GetString("ScreenSaverConfig_exe", resourceCulture);
            }
        }
        
        internal static byte[] ServerCycleConnectAttempt {
            get {
                object obj = ResourceManager.GetObject("ServerCycleConnectAttempt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitors Oxigen&apos;s remote server for new content and software updates.
        /// </summary>
        internal static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        internal static byte[] ss_general_data {
            get {
                object obj = ResourceManager.GetObject("ss_general_data", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TaxonomySearch {
            get {
                object obj = ResourceManager.GetObject("TaxonomySearch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TimeSpanObjectWrapper {
            get {
                object obj = ResourceManager.GetObject("TimeSpanObjectWrapper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] UserSettings {
            get {
                object obj = ResourceManager.GetObject("UserSettings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WCFErrorReporting {
            get {
                object obj = ResourceManager.GetObject("WCFErrorReporting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WindowsVersionDetection {
            get {
                object obj = ResourceManager.GetObject("WindowsVersionDetection", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] XmlSerializableGenericDictionary {
            get {
                object obj = ResourceManager.GetObject("XmlSerializableGenericDictionary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] XmlSerializableSortableGenericList {
            get {
                object obj = ResourceManager.GetObject("XmlSerializableSortableGenericList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] XMLSerializer {
            get {
                object obj = ResourceManager.GetObject("XMLSerializer", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
